### ISSUE TITLE
`block in run': undefined method

### ISSUE THREAD

**Issue by sergiopvilar** [danchoi/kindlerb#2]
Hello, I'm trying to create a new .mobi file with kindlerb but I get the following error with this file tree:

![File tree](http://s16.postimg.org/wlym95v79/Captura_de_Tela_2013_07_27_s_12_14_15.png)

```
/Users/sergiovilar/.rvm/gems/ruby-1.9.3-p362/gems/kindlerb-0.1.1/lib/kindlerb.rb:112:in `block in run': undefined method `[]' for nil:NilClass (NoMethodError)
from /Users/sergiovilar/.rvm/gems/ruby-1.9.3-p362/gems/kindlerb-0.1.1/lib/kindlerb.rb:37:in `chdir'
from /Users/sergiovilar/.rvm/gems/ruby-1.9.3-p362/gems/kindlerb-0.1.1/lib/kindlerb.rb:37:in `run'
from /Users/sergiovilar/.rvm/gems/ruby-1.9.3-p362/gems/kindlerb-0.1.1/bin/kindlerb:8:in `<top (required)>'
from /Users/sergiovilar/.rvm/rubies/ruby-1.9.3-p362/bin/kindlerb:23:in `load'
from /Users/sergiovilar/.rvm/rubies/ruby-1.9.3-p362/bin/kindlerb:23:in `<main>'
```

**Comment by MoOmEeN** [comment]
That was long long tme ago, but: did you solve the issue? I am facing similar

**Comment by danchoi** [comment]
Sorry I don't have time to address this issue now. Volunteer patches would
be welcome, as would anyone who would like to take over this project as
maintainer.

**Comment by MoOmEeN** [comment]
thanks for the reply, but the issue was really silly, that silly that I removed my comment ;)
I was missing 'sections' directory (same as @sergiovilar), once I added it, everything worked.
thanks

**Comment by sergiovilar** [comment]
@MoOmEeN I wrote a library in PHP, maybe you can use https://github.com/sergiovilar/Kindle-Periodical

**Comment by MoOmEeN** [comment]
@sergiovilar thanks, I made kindlerb working, but I will take a look.
